artifacts_root: artifacts



data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip
  local_data_file: artifacts/data_ingestion/SamsumData.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]